<div class="centerlabel-container">
	<h2 class="step">Step 2</h2>
	<div class="centerlabel-text">
		<a href="javascript:rb.editCenterArtClick();">
			<p><?php echo $this->__('Center Image');?></p>
		</a>
		<a href="javascript:rb.editCenterArtClick();" id="edit-center-art">
			<?php echo $this->__('Edit');?>
		</a>
	</div>
	<a href="javascript:rb.editCenterArtClick();" >
	<img src="<?php echo $this->getSkinUrl('images/centerlabel-placeholder.png') ?>" width="84" id="center-art-thumb">
	</a>
</div>