

<div class="reorder-strip-container">
	<ul class="frame-list">
		<li class="frames frame-1"><?php echo $this->__('Frame 1') ?></li>
		<li class="frames frame-2"><?php echo $this->__('Frame 2') ?></li>
		<li class="frames frame-3"><?php echo $this->__('Frame 3') ?></li>
		<li class="frames frame-4"><?php echo $this->__('Frame 4') ?></li>
		<li class="frames frame-5"><?php echo $this->__('Frame 5') ?></li>
		<li class="frames frame-6"><?php echo $this->__('Frame 6') ?></li>
		<li class="frames frame-7"><?php echo $this->__('Frame 7') ?></li>
	</ul>

</div>
