<div class="tool-container" id="container-help-buttons">
	<div class="help-buttons-container">
		<div class="help-buttons guidelines-link">
			<a href="javascript:rb.helpOverlay();"><?php echo $this->__('Reel Creation Help') ?></a>
		</div> 
		<div class="help-buttons howto-video-link">
			<a href="javascript:rb.howtoOverlay();"><?php echo $this->__('Watch How to Build a Reel Video') ?></a>
		</div>
	</div>
</div>