

<div class="mobile-header">
	<div class="header-frame">Frame <span>1</span></div>
	<div class="header-save-preview">
		<p>
			<a id="h-save" href="#">Save</a>
			<a id="h-return" href="#">Return</a>
		</p>
	</div>
</div>

<div class="mobile-image-upload">
	<a class="reel-arrow-left" href="#"></a>
	<a class="m-image-upload" href="#">Click or tap this frame<br/>to upload an image</a>
	<a class="reel-arrow-right" href="#"></a>
</div>
