

<!-- FRAME REORDER -->
<div class="frame-swipeup">
	<div class="swipe-indicator">
		<a class="swipe-up-icon" href="#"></a>
		<a class="swipe-up-text" href="#">Swipe up for Frame Index</a>
	</div>
	<div class="swipe-content">
		<p>Click and Drag to Rearrange</p>
		<ul class="swipe-frames">
			<li>Frame 1</li>
			<li>Frame 2</li>
			<li>Frame 3</li>
			<li>Frame 4</li>
			<li>Frame 5</li>
			<li>Frame 6</li>
			<li>Frame 7</li>
		</ul>
		<a href="#">
			<p>Done Reordering</p>
			<span></span>
		</a>
	</div>
</div>