<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="dashboard">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customeraccount-special-notices')->toHtml(); ?>
    <div class="page-title">
        <h1><?php echo $this->__('My Account') ?></h1>
    </div>


    <div id="ios-app-marketing" style="display: none;">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('ios-dashboard-popup')->toHtml(); ?>
    </div>

    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('create-new-reel-dashboard')->toHtml(); ?>
    <?php echo $this->getChildHtml('top') ?>
<!--    <div class="box-account box-info">
        <div class="box-head">
            <h2><?php echo $this->__('Account Information') ?></h2>
        </div>
-->
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <?php echo $this->getChildHtml('address') ?>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>

<script>


    var onclickGoToIosStore = function(url) {
        category = 'mobile_outlink';
        action = 'ios_popup';
        label = 'click';
        value = 1;

        _gaq.push(['_trackEvent', category, action, label, value, '1']);
        var win = window.open(url, '_blank');
        win.focus();

        return true;
    };


    jQuery(document).ready(function() {


        // 20190611 ios marketing popup
        <?php if(Mage::helper('chimage3d/marketing')->getShouldShowIosPopup()): ?>


        jQuery($j('#ios-app-marketing')[0].innerHTML).dialog({
                modal : true,
                left: '50%',
                top: '18%',
                'margin-left': '-350px',
            beforeClose: function( event, ui ) {
                category = 'mobile_outlink';
                action = 'ios_popup';
                label = 'no-click';
                value = 1;
                _gaq.push(['_trackEvent', category, action, label, value, '1']);

            },
        });

    <?php endif; ?>

        // 20190611 iso marketing popup

	var winWidth = jQuery(window).width();
        var useMobile = true;
	var currentHref = jQuery('.create-new-container').find('a').attr('href');
	var newHref = currentHref.replace('reelbuilder', 'reelbuilder/index/mobile');

	if(winWidth < 925 && useMobile) {
                        jQuery('.create-new-container').find('a').attr('href', newHref);
        }

        jQuery('ul.messages').prependTo('div.col2-left-layout');
	var ua = window.navigator.userAgent;
	var uav = 0;
        var browserNeedsUpgrade = false;
	var msie = ua.indexOf("MSIE");
	if (msie > 0) {    // If Internet Explorer, return version number
        	uav = parseInt (ua.substring (msie+5, ua.indexOf (".", msie )));
	}
	if(uav > 0 && uav < 9) {
		browserNeedsUpgrade = true;
	}

        if(browserNeedsUpgrade) {
            jQuery('.create-new-container').hide();
            jQuery('.upgrade-browser-note').show();
        }
    });

</script>
