<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>

<?php $_product = $this->getProduct();
$customOptionsBlock =  $this->getLayout()->createBlock('catalog/product_view_options_type_text');
$customOptionsBlock->setProduct($_product);

$customOptionTextFile = 'catalog/product/view/options/type/text.phtml';
$customOptionSelectFile = 'catalog/product/view/options/type/select.phtml';

$customOptionsBlock->setTemplate($customOptionTextFile); // $customOptionSelectFile

;

?>

<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()); ?>
<?php if ($_product->isSaleable()):?>
    <?php if (count($_options)): ?>
        <?php $helper = Mage::helper('collinsharper_chcategoryforms'); ?>
            <?php if($formCategoryJson = $helper->getFormProductData($_product)):
            $_options = $helper->getKeyedOptionArray($_options);
            $_customOptions = $helper->getKeyedOptionArray(Mage::helper('core')->decorateArray($_product->getOptions()));
            ?>
        <script type="text/javascript">
            //<![CDATA[
            var chForm = new productForm();
            var chFormJson = <?php echo json_encode($formCategoryJson); ?>;
            jQuery( document ).ready(function() {
                chForm.setFormData(chFormJson);
                chForm.formAction = '<?php echo $this->getUrl('chcategoryforms/index/process/', array("_secure"=>true)); ?>';
                chForm.checkAction = '<?php echo $this->getUrl('chcategoryforms/index/check/', array("_secure"=>true)); ?>';
                chForm.loginAction = '<?php echo $this->getUrl('customer/account/login/', array("_secure"=>true)); ?>';
                // general setup
                <?php  echo (isset($formCategoryJson['initial']['step_js']) ? $formCategoryJson['initial']['step_js'] : ''); ?>
                // general setup
            });
            //]]>
                </script>
            <div class="formdescrption"><?php echo  $formCategoryJson['initial']['step_description']; ?></div>
<ul class="form-slide form-slide-agree opc" style="display: block;">
            <ul class="form-list">
            <?php foreach($formCategoryJson['steps'] as $stepIdNum => $step):?>
                <?php $stepIdNum++; ?>
                    <?php $stepId = isset($step['step_id']) && $step['step_id'] ? $step['step_id'] : strtolower(preg_replace('/[^a-z0-9]/i', '', $step['step_name'])); ?>
                <li class="wide section"> 
                    <div class="step-title chformtitle_<?php echo ($stepIdNum) . ' steptitle_' . $stepId; ?>" style="display:none" id="chformtitle_<?php echo $stepId; ?>" >

                     <!--   <span class="number"><?php echo ($stepIdNum); ?></span> -->
                        <h2 class="step-name"><?php echo $step['step_name']; ?></h2>
                     <!--   <a href="#"><?php echo $this->__('Edit'); ?></a> -->
                        <div class="step-description"><?php echo $step['step_description']; ?></div>
                    </div>
                    <div class="step chformstep_<?php echo ($stepIdNum) . ' step_' . $stepId; ?>" style="display:none" id="chformstep_<?php echo $stepId; ?>">
                        <?php foreach ($step['step_options'] as $stepOptionId => $stepOptionName): ?>
                        <?php $_option = isset($_options[$stepOptionId]) ? $_options[$stepOptionId]  : false ?>
                        <?php if (!$_option || !$_option->getSelections()):
                            mage::log(__FILE__ . " failed to find step option " . print_r($step,1)); ?>
                            <?php continue; ?>
                            <?php endif; ?>
                        <?php echo $this->getOptionHtml($_option) ?>
                        <?php endforeach; ?>

                        <?php

                        foreach ($step['step_custom_options'] as $stepOptionId => $stepOptionName): ?>
                        <?php $_option = isset($_customOptions[$stepOptionId]) ? $_customOptions[$stepOptionId]  : false ?>
                        <?php if (!$_option):
                            mage::log(__FILE__ . " failed to find CUSTOM step option " . print_r($step,1)); ?>
                            <?php continue; ?>
                            <?php endif; ?>
                            <div id="<?php echo strtolower(preg_replace('/[^a-z0-9]+/i','', 'custom option' . $stepOptionName)); ?>" style="display:none" class="custom-options"><?php
                                $customOptionsBlock->setTemplate($customOptionTextFile);

                                    // WE ONLY support text fields.
                                if($_option->getType() == 'drop_down') {
                              //      $customOptionsBlock->setTemplate($customOptionSelectFile);
                                }

                                $optBlock = $customOptionsBlock
                                ->setOption($_option)
                                ->toHtml();
                            echo str_replace('onchange="opConfig.reloadPrice()"','', $optBlock);
                            ?></div>
                        <?php endforeach; ?>

                        <div class="buttons">
                        <?php if(isset($step['step_buttons']) && strlen(trim($step['step_buttons'])) > 3): ?>
                        <?php echo $step['step_buttons']; ?>
                        <?php else: ?>
                        <?php if($stepIdNum != 0): ?>
                            <div class="step-back-buttons sprites-arrow-back">
                                <button type="button" title="<?php echo $this->__('Back');?>" class="button btn-back" onclick="chForm.backStep(<?php echo ($stepIdNum); ?>, 'chformstep_<?php echo $stepId; ?>')"><span><span><?php echo $this->__('Back');?></span></span></button>
                            </div>
                                <?php endif; ?>
                            <div class="step-addtoorder-buttons">
                                <button type="button" title="<?php echo $this->__('Next');?>" class="button btn-addtoorder" onclick="chForm.nextStep(<?php echo ($stepIdNum); ?>, 'chformstep_<?php echo $stepId; ?>')"><span><span><?php echo $this->__('Next');?></span></span></button>
                            </div>
                        <?php endif; ?>
                    </div>
                    </div>
                </li>
            <?php endforeach; ?>


            </ul>
</ul>

                <?php endif;?>

    <?php else: ?>
        <p><?php echo $this->__('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
<?php

$isLoggedIn = Mage::getSingleton("customer/session")->isLoggedIn();
$showAddressSteps = true; // && $isLoggedIn
?>


<div id="billing_address" style="display:none">
    <?php
    try {


    echo  Mage::app()->getLayout()->createBlock("checkout/onepage_shipping")->setName('checkout.onepage.shipping.form')->setTemplate('chcategoryform/address.phtml')->toHtml();

} catch ( Exception $e ) {
    mage::log(__FILE__ . " Exception " . $e->getMessage());
}
?></div>

<div id="payment_block"   style="display:none" >
    <?php //if(Mage::getSingleton("customer/session")->isLoggedIn()) {
  //  echo  Mage::app()->getLayout()->createBlock('checkout/onepage_payment')->setName('checkout.onepage.payment')->setTemplate('chcategoryform/payment.phtml')->toHtml();
    //echo  Mage::app()->getLayout('checkout')->getBlock('checkout.onepage.payment');

   // }

    echo $this->getLayout()
        ->createBlock('page/html')
        ->setBlockId("bs_cards")
        ->setTemplate('beanstreamprofiles/customer/form_cards.phtml')
        ->toHtml();


/*
    echo $this->getLayout()
    ->createBlock('authorizenetcim/ccnew')
    ->setBlockId("authorizenetcim_ccnew")
    ->setTemplate('authorizenetcim/ccNew.phtml')
    ->toHtml();
    */
    ?>

    </div>

<div id="images_step" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_images')->toHtml(); ?>
</div>

<div id="images_step_jpg" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_images_jpg')->toHtml(); ?>
</div>

<div id="images_step_mpo" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_images_mpo')->toHtml(); ?>
</div>

<div id="images_step_previous" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_images_reorder')->toHtml(); ?>
</div>


<div id="images_step_mail" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_images_mail')->toHtml(); ?>
</div>

<div id="center_art" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_center_art')->toHtml(); ?>
</div>

<div id="shipping_step" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_shipping')->toHtml(); ?>
</div>


<div id="terms_agreements" style="display:none">
    <?php echo $this->getLayout()->createBlock('checkout/agreements')->setBlockId('checkout.onepage.agreements')->setTemplate('checkout/onepage/agreements.phtml')->toHtml(); ?>
</div>

<div id="stereo_order_final_step" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_final_step')->toHtml(); ?>
</div>

<div id="stereo_order_confirm" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('stereo_order_confirm')->toHtml(); ?>
</div>


<span id="form-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
