<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>

<?php 
$_product = $this->getProduct();
$customOptionsBlock =  $this->getLayout()->createBlock('catalog/product_view_options_type_text');
$customOptionsBlock->setProduct($_product);
$customOptionTextFile = 'catalog/product/view/options/type/text.phtml';
$customOptionSelectFile = 'catalog/product/view/options/type/select.phtml';
$customOptionsBlock->setTemplate($customOptionTextFile); // $customOptionSelectFile
?>

<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()); ?>
<?php if ($_product->isSaleable()):?>
    <?php if (count($_options)): ?>
        <?php $helper = Mage::helper('collinsharper_chcategoryforms'); ?>
		<?php if($formCategoryJson = $helper->getFormProductData($_product)):
		$_options = $helper->getKeyedOptionArray($_options);
		$_customOptions = $helper->getKeyedOptionArray(Mage::helper('core')->decorateArray($_product->getOptions())); ?>
		
		<script type="text/javascript">
		//<![CDATA[
			var chForm = new productForm();
			var chFormJson = <?php echo json_encode($formCategoryJson); ?>;
			jQuery(document).ready(function() {
				chForm.setFormData(chFormJson);
				chForm.formAction = '<?php echo $this->getUrl('chcategoryforms/index/process/', array("_secure"=>true)); ?>';
				// general setup
				<?php  echo (isset($formCategoryJson['initial']['step_js']) ? $formCategoryJson['initial']['step_js'] : ''); ?>
				// general setup
			});
		//]]>
		</script>
	
        <div class="formdescrption"><?php echo  $formCategoryJson['initial']['step_description']; ?></div>
		<ul class="form-slide form-slide-agree opc" style="display: block;">
            <ul class="form-list">
            <?php foreach($formCategoryJson['steps'] as $stepIdNum => $step):?>
                <?php $stepIdNum++; ?>
                <?php $stepId = isset($step['step_id']) && $step['step_id'] ? $step['step_id'] : strtolower(preg_replace('/[^a-z0-9]/i', '', $step['step_name'])); ?>
                <li class="wide section"> 
                    <div class="step-title chformtitle_<?php echo ($stepIdNum) . ' steptitle_' . $stepId; ?>" style="display:none" id="chformtitle_<?php echo $stepId; ?>" >

                     <!--   <span class="number"><?php echo ($stepIdNum); ?></span> -->
                        <h2 class="step-name"><?php echo $step['step_name']; ?></h2>
                     <!--   <a href="#"><?php echo $this->__('Edit'); ?></a> -->
                        <div class="step-description"><?php echo $step['step_description']; ?></div>
                    </div>
                    <div class="step chformstep_<?php echo ($stepIdNum) . ' step_' . $stepId; ?>" style="display:none" id="chformstep_<?php echo $stepId; ?>">
                        <?php foreach ($step['step_options'] as $stepOptionId => $stepOptionName): ?>
                        <?php $_option = isset($_options[$stepOptionId]) ? $_options[$stepOptionId]  : false ?>
                        <?php if (!$_option || !$_option->getSelections()):
                            mage::log(__FILE__ . " failed to find step option " . print_r($step,1)); ?>
                            <?php continue; ?>
                            <?php endif; ?>
                        <?php echo $this->getOptionHtml($_option) ?>
                        <?php endforeach; ?>

                        <?php foreach ($step['step_custom_options'] as $stepOptionId => $stepOptionName): ?>
                        <?php $_option = isset($_customOptions[$stepOptionId]) ? $_customOptions[$stepOptionId]  : false ?>
                        <?php if (!$_option):
                            mage::log(__FILE__ . " failed to find CUSTOM step option " . print_r($step,1)); ?>
                            <?php continue; ?>
                            <?php endif; ?>
                            <div id="<?php echo strtolower(preg_replace('/[^a-z0-9]+/i','', 'custom option' . $stepOptionName)); ?>" style="display:none" class="custom-options"><?php
                                $customOptionsBlock->setTemplate($customOptionTextFile);

                                // WE ONLY support text fields.
                                if($_option->getType() == 'drop_down') {
								// $customOptionsBlock->setTemplate($customOptionSelectFile);
                                }

                                $optBlock = $customOptionsBlock
                                ->setOption($_option)
                                ->toHtml();
								echo str_replace('onchange="opConfig.reloadPrice()"','', $optBlock); ?>
							</div>
                        <?php endforeach; ?>

                        <div class="buttons">
							<?php if(isset($step['step_buttons']) && strlen(trim($step['step_buttons'])) > 3): ?>
							<?php echo $step['step_buttons']; ?>
							<?php else: ?>
							<?php if($stepIdNum != 0): ?>
								<div class="step-back-buttons sprites-arrow-back">
									<button type="button" title="<?php echo $this->__('Back');?>" class="button btn-back" onclick="chForm.backStep(<?php echo ($stepIdNum); ?>, 'chformstep_<?php echo $stepId; ?>')"><span><span><?php echo $this->__('Back');?></span></span></button>
								</div>
									<?php endif; ?>
								<div class="step-addtoorder-buttons sprites-orange-nextarrow">
									<button type="button" title="<?php echo $this->__('Next');?>" class="button btn-addtoorder" onclick="chForm.nextStep(<?php echo ($stepIdNum); ?>, 'chformstep_<?php echo $stepId; ?>')"><span><span><?php echo $this->__('Next');?></span></span></button>
								</div>
							<?php endif; ?>
						</div>
                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
		</ul>
	<?php endif;?>

    <?php else: ?>
        <p><?php echo $this->__('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>

<div id="billing_address" style="display:none">
<?php
    try {
		echo  Mage::app()->getLayout()->createBlock("checkout/onepage_billing")->setName('checkout.onepage.billing.form.custom')->setTemplate('chcategoryform/bill_address.phtml')->toHtml();
	} catch ( Exception $e ) {
		mage::log(__FILE__ . " B ADDRESS Exception " . $e->getMessage());
	}
?>
</div>

<div id="shipping_address" style="display:none">
<?php
    try {
		//echo Mage::app()->getLayout()->createBlock("checkout/onepage_shipping")->setName('checkout.onepage.shipping.form.custom')->setTemplate('chcategoryform/address.phtml')->toHtml();
	     echo $this->getLayout()
    ->createBlock('customer/address_edit')
    ->setBlockId('customer_address_edit_custom_contact')
    ->setName('finalorder-customer_address_edit')
    ->setTitle('Contact Address')
    ->setPrefix('contact-')
    ->setTemplate('chcategoryform/customer_address.phtml')
    ->toHtml();

    } catch ( Exception $e ) {
		mage::log(__FILE__ . " S ADDRESS Exception " . $e->getMessage());
	}
?></div>

<div id="payment_block"   style="display:none" >
    <?php
    echo $this->getLayout()
        ->createBlock('page/html')
        ->setBlockId("bs_cards")
        ->setSkipBilling(true)
        ->setTemplate('beanstreamprofiles/customer/form_cards.phtml')
        ->toHtml();
    ?>
</div>

<div id="loginregister_step" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('b2b_order_register_login_guest')->toHtml(); ?>
</div>

<div id="quotedetails_step" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('b2b_order_quotedetails')->toHtml(); ?>
</div>

<div id="order_paymentstep" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('b2b_order_paymentstep')->toHtml(); ?>
</div>

<div id="order_proofstep" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('b2b_order_proofinformation')->toHtml(); ?>
</div>

<div id="proofaddress" style="display:none">
	<?php echo $this->getLayout()
	->createBlock('customer/address_edit')
	->setBlockId('customer_address_edit_custom_proof')
	->setName('proof-customer_address_edit')
	->setTitle('Shipping Address for the PROOF')
	->setPrefix('proof-')
	->setTemplate('chcategoryform/customer_address.phtml')
	->toHtml(); ?>
</div>

<div id="finalorderaddress" style="display:none">
    <?php echo $this->getLayout()
    ->createBlock('customer/address_edit')
    ->setBlockId('customer_address_edit_custom_finalorder')
    ->setName('finalorder-customer_address_edit')
    ->setTitle('Shipping Address for the FINAL ORDER')
    ->setPrefix('finalorder-')
    ->setTemplate('chcategoryform/customer_address.phtml')
    ->toHtml(); ?>
</div>

<div id="order_deliveryinformation" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('b2b_order_deliveryinformation')->toHtml(); ?>
</div>

<div id="terms_agreements" style="display:none">
    <?php echo $this->getLayout()->createBlock('checkout/agreements')->setBlockId('checkout.onepage.agreements')->setTemplate('checkout/onepage/agreements.phtml')->toHtml(); ?>
</div>

<div id="termsstep" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('b2b_order_termsstep')->toHtml(); ?>
</div>

<div id="almostthere" style="display:none">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('b2b_order_almostthere')->toHtml(); ?>
</div>

<div id="order_date_field"  style="display:none">
    <ul>
        <li>
            <label for="order_date"><?php echo $this->__('Order Date'); ?></label>
            <input name="order_date" id="order_date" value="" title="<?php echo $this->__('Order Date'); ?>" type="text" class=" input-text" />
        </li>

        <li>
            <label for="purchase_order_number">Purchase Order Number:</label><input type="text" name="purchase_order_number" id="purchase_order_number" value="" size="20" />
        </li>
    </ul>
</div>

<script type="text/javascript">
    //<![CDATA[
    jQuery( "#order_date" ).datepicker({ dateFormat: "mm-dd-yy" });
    jQuery( "#in_hands_date" ).datepicker({ dateFormat: "mm-dd-yy" });
    //]]>
</script>

