<?php

/*
 * Include common stuff first:
 */
$_item = $this->getItem();
$item_id = $_item->getId();

$redeemListId = 'points-list-redeemed-'. $item_id;

/*
 * include specific templates:
 */
if (Mage::helper('rewards/theme')->getPackageName() === "rwd") {
    include 'downloadable_rwd.phtml';
    
} else if (Mage::helper('rewards/version')->isMageVersionAtLeast('1.8.1.0')) {
    	 include 'downloadable_m1901.phtml';

} else if (Mage::helper('rewards/version')->isMageVersionAtLeast('1.7.0.0')) {
    	 include 'downloadable_m1800.phtml';
    	 
} else {
	include 'downloadable_m1620.phtml';
}

?>