<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Select */ ?>
<?php $_option      = $this->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $this->_getDefaultValues(); ?>
<?php $tierPriceHtml = ''; ?>
<?php $customClass = strtolower(preg_replace('/[^a-z0-9]/i', '', $_option->getTitle())); ?>
<?php $customQtyClass = strtolower(preg_replace('/[0-9]/', '', $customClass)); ?>

<div class="bundleoptionwrapper wrapper_<?php echo $customClass;?>">
<dt>
    <label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->escapeHtml($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label>
</dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
    <?php /** @var $_selection Mage_Catalog_Model_Product*/ ?>
    <?php if ($this->_showSingle()): ?>
        <div class="select-tier-price">
            <?php //echo $this->getSelectionTitlePrice($_selections[0]); ?>
            <?php if ($_selections[0]->getSelectionCanChangeQty()): ?>
                <?php $tierPriceHtml = $this->getTierPriceHtml($_selections[0]); ?>
        </div>
        <?php endif; ?>
        <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>"/>
    <?php else:?>
        <select onchange="bundle.changeSelection(this)" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $_option->getId() ?>]" class="bundle-option-<?php echo $_option->getId() ?><?php if ($_option->getRequired()) echo ' required-entry' ?> bundle-option-select change-container-classname <?php echo $customClass; ?>">
            <option value=""><?php echo $this->__('Choose a selection...') ?></option>
        <?php foreach ($_selections as $_selection): ?>
            <?php if ($_selection->getSelectionCanChangeQty() && $this->_isSelected($_selection)): ?>
                <?php $tierPriceHtml = $this->getTierPriceHtml($_selection); ?>
            <?php endif; ?>
            <option value="<?php echo $_selection->getSelectionId() ?>"<?php if ($this->_isSelected($_selection)) echo ' selected="selected"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>><?php echo trim(str_replace('+$0.00', '', $this->getSelectionTitlePrice($_selection, false))) ?></option>
        <?php endforeach; ?>
        </select>
    <?php endif; ?>
    </div>
    <span class="qty-holder qty-<?php echo $customQtyClass ;?>">
        <label for="bundle-option-<?php echo $_option->getId() ?>-qty-input"><?php echo $this->__('Qty:') ?>&nbsp;</label><input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?> qty_<?php echo $customClass; ?>" type="text" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>"/>
    </span>
    <span id="bundle-option-<?php echo $_option->getId() ?>-tier-prices"> <?php echo $tierPriceHtml; ?></span>
</dd>
</div>
