<?php 
$base_url = Mage::app()->getStore()->isCurrentlySecure() ? Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) : Mage::getBaseUrl();
?>
<style>
    .shipping_method_options{margin:0 0 0 20px;}
    .update_item{margin: 10px 0 10px 0;}
.shipment-methods dt { margin-top: 5px; margin-bottom: 5px; font-weight: bold; }
.shipment-methods dt.secondary_dt {
	margin-left: 5px;
	color: #333;
}
.shipment-methods ul li {
	line-height: 20px;
	margin-left: 5px;
}
.shipment-methods input {
	margin-bottom: 3px;
}
ul.ch_inline {
	padding: 0px;
}
ul.ch_inline li {
	display: inline;
	padding: 0px;
	margin: 0px;
}
#nearest_office {
	padding-top: 2px;
}
#postcode {
	 height: 19px;
    margin-top: 3px;
}
#postcode:disabled {
	border: 1px solid #999;
	background-color: #ddd;
	color: #666;
}
#update_office_list:disabled {
		border: 1px solid #999;
	background-color: #ddd;
	color: #666;
}
#update_office_list:disabled span {
	background-color: #ddd;
	border: none;
	color: #666;
}
	
</style>
<p><?php echo $this->__('Please note changing the shipping method will not alter the price of shipping or charges on the order'); ?></p>
<form method="POST" action="<?php echo Mage::helper("adminhtml")->getUrl('*/switch/save', array()); ?>" id="change_shipping_method_form">
     <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /> 
     <input name="quote_id" type="hidden" value="<?php echo $this->getQuote()->getId(); ?>" /> 
<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_Create_Shipping_Method_Form */ ?>
    <?php $_shippingRateGroups = $this->getAddress()->setCollectShippingRates(true)->collectShippingRates()->getGroupedAllShippingRates(); ?>

<?php if ($_shippingRateGroups): ?>
    <div id="order-shipping-method-choose" style="display:none">
    <dl class="shipment-methods">
    <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
        <dt>
            <strong><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></strong>
		</dt>
		<?php if ($code == 'chcanpost2module'): ?>
		<dt class="secondary_dt">
			<?php echo $this->__('Shipping Service'); ?>
		</dt>   
		<?php endif;?>
		
			<ul>
            <?php $show_office_list = false; ?>
            <?php foreach ($_rates as $_rate): ?>
                <?php 
                    $_radioProperty = 'name="order[shipping_method]" type="radio"';
                    $_code=$_rate->getCode();                     
                    if ($code == 'chcanpost2module' && $this->isMethodActive($_code)) {
                        $show_office_list = true;
                    } 
                ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages">
                            <li class="error-msg"><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li>
                        </ul>
                   <?php else: ?>
                        <?php $method_description = $this->escapeHtml($this->getCarrierName($code)).' '.$this->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()); ?>
                        <?php $_checked = $this->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                        <input <?php echo $_radioProperty ?> value="<?php echo $_code ?>" id="s_method_<?php echo $_code ?>" <?php echo $_checked ?> onchange="updateOptions(this.value);" />
                        <input name="shipping_method_description[<?php echo $_code ?>]" type="hidden" value="<?php echo $method_description; ?>" /> 
                        <label class="normal" for="s_method_<?php echo $_code ?>" id="s_label_method_<?php echo $_code ?>">
                            <?php echo $method_description; ?>
                            <strong>
                                <?php echo Mage::helper('core')->currency($_rate->getPrice(), true, false); ?>
                            </strong>
                        </label>
                   <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
		
			<?php if ($code == 'chcanpost2module'): ?>
			<dt class="secondary_dt" id="shipping_options_title">
				<?php echo $this->__('Shipping Options'); ?>
			</dt>   
			<?php endif;?>		
		
			<dd>
		
            <?php if ($code == 'chcanpost2module'): ?>
            <div class="shipping_method_options">   
                <input type="checkbox" name="signature" class="cp_option" id="option_SO" />
                <label for="signature"><?php echo __('Require Signature'); ?></label>
            </div>
            <?php endif; ?>
            <?php if ($code == 'chcanpost2module' && Mage::getStoreConfig('carriers/chcanpost2module/require_coverage') == 'optional'): ?>
            <div class="shipping_method_options">
                <input type="checkbox" name="coverage" class="cp_option" id="option_COV" />
                <label for="coverage"><?php echo __('Include Coverage'); ?></label>
            </div>
            <?php endif; ?>
            <?php if ($code == 'chcanpost2module' && Mage::getStoreConfig('carriers/chcanpost2module/card_for_pickup')): ?>
            <div class="shipping_method_options">
                <input type="checkbox" name="card_for_pickup" class="cp_option" id="option_HFP" />
                <label for="card_for_pickup"><?php echo __('Card for Pick Up'); ?></label>
            </div>
            <?php endif; ?>
            <?php if ($code == 'chcanpost2module' && !Mage::helper('chcanpost2module/option')->isPaOption('admin', $this->getQuote()) && Mage::getStoreConfig('carriers/chcanpost2module/do_not_safe_drop')): ?>
            <div class="shipping_method_options">
                <input type="checkbox" name="do_not_safe_drop" class="cp_option" id="option_DNS" />
                <label for="do_not_safe_drop"><?php echo __('Do not Safe Drop'); ?></label>
            </div>
            <?php endif; ?>
            <?php if ($code == 'chcanpost2module' && !Mage::helper('chcanpost2module/option')->isPaOption('admin', $this->getQuote()) && Mage::getStoreConfig('carriers/chcanpost2module/leave_at_door')): ?>
            <div class="shipping_method_options">
                <input type="checkbox" name="leave_at_door" class="cp_option" id="option_LAD" />
                <label for="leave_at_door"><?php echo __('Leave at Door (Do not card)'); ?></label>
            </div>
            <?php endif; ?>

        </dd>
    <?php endforeach; ?>
    </dl>
    <br /><br />
    <input type="submit" value="<?php echo __('Save new shipping method'); ?>"/>
    </div>
</form>
<script type="text/javascript">$('order-shipping-method-choose').show();</script>
<?php elseif($this->getIsRateRequest()): ?>
    <strong><?php echo Mage::helper('sales')->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
    <div id="order-shipping-method-summary">
        <a href="#" onclick="order.loadShippingRates();return false">
            <?php echo Mage::helper('sales')->__('Get shipping methods and rates') ?>
        </a>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry" />
    </div>
<?php endif; ?>
<div style="display:none;" id="shipping-method-overlay" class="overlay"><span><?php echo $this->__('Shipping method selection is not applicable') ?></span></div>
<script type="text/javascript">
function updateOptions(method_code) {
    if (method_code.indexOf('chcanpost2module') == 0) {
        if ($('shipping-method-please-wait')) {
            $('shipping-method-please-wait').show();
        }
        $$('input[type="checkbox"]').each(function(el){ 
            el.disabled = true; 
            el.checked = false; 
        });
        new Ajax.Request('<?php echo $base_url; ?>admin/switch/getOptions', {
          method:'post',
          parameters: {
              method_code: method_code,
              quote_id: '<?php echo $this->getQuote()->getId(); ?>'
          },
          requestHeaders: {Accept: 'application/json'},
          onSuccess: function(response) {
              var json = response.responseText.evalJSON();  
              if (json != '') {              
                  for (var i = 0; i < json.options.length; i++) {
                      if ($('option_' + json.options[i])) {
                          $('option_' + json.options[i]).disabled = false;
                      }
                  }
              }
          }
        });
        if ($('shipping-method-please-wait')) {
            $('shipping-method-please-wait').hide();
        }
    }
}
</script>